public  class Address {
    public void homeAddress(){
       String name = 'Zeynep';
       system.debug('Your name '+ name);

       Integer numFamily = 5;
       system.debug('Total number of members in your family '+ numFamily);

       String houseName = 'Flower';
       system.debug('House name '+ houseName);

       Integer houseNumber = 10;
       system.debug('House number '+ houseNumber);

       String streetName = 'Calderwood Dr.';
       System.debug('Street Name ' + streetName);

       String cityName = 'Antioch';
       System.debug('City Name '+ cityName);

       String stateName = 'Tennesse';
       System.debug('State name '+ stateName);

       String ISOcode = 'TN4627';
       System.debug('State ISO code '+ ISOcode);


       String CountryName = 'US';
       System.debug('Country name '+ CountryName); 

       String cauntryISOcode= 'US7448';
       System.debug('Cauntry ISO code '+ cauntryISOcode);

       String zipCode = '37013';
       System.debug('Zip code '+ zipCode);

       Boolean currentHome = true;
       System.debug('Is this your current home or not? '+ currentHome);
           
       }
  
    }

