//decimal return1 = calculator.dynamicCalulationMethod(1, 2, 'addition');
//system.debug(return1);

system.debug(calculator.dynamicCalulationMethod(5, 3, 'addition'));
system.debug(calculator.dynamicCalulationMethod(10, 20, 'substriction'));
system.debug(calculator.dynamicCalulationMethod(26, 10,'multiplication' ));
system.debug(calculator.dynamicCalulationMethod(1, 6, 'division'));
system.debug(calculator.dynamicCalulationMethod(1, 2, 'hshsj'));