Planets Earth = new planets();
Earth.planetName = 'Earth';
Earth.planetNumber = 3;
Earth.numberMoons = 4;
system.debug(Earth);
//to make separate lines on the console
System.debug(Earth.planetName);
System.debug(Earth.planetNumber);
System.debug(Earth.numberMoons);



Planets jupiter = new Planets();
jupiter.planetName = 'jupiter';
jupiter.numberMoons = 9;
jupiter.planetNumber = 7;
system.debug(jupiter);
